name: Deploy to GHCR

on:
  push:
    branches:
      - 'main'

jobs:
  
  run-ssh-command:
    runs-on: ubuntu-latest
    steps:
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: printf "test:test\ntest2:test2\n" > .env
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: run-ssh-command
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/helper-bot:${{ github.sha }}
